# Generated by Django 4.2.16 on 2025-04-15 15:41

import django.core.validators
from django.db import migrations, models
import meldung.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('kennung', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('jahrgangsstufe', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(13)], verbose_name='Jahrgangsstufe')),
                ('geschlecht', models.CharField(choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers')], max_length=1, verbose_name='Geschlecht')),
                ('zeitpunkt_erstellung', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Meldung')),
                ('zeitpunkt_vorfall', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt des Vorfalls')),
                ('ort', models.CharField(choices=[('Toilette', 'Toilette'), ('Klassenraum', 'Klassenraum'), ('Flur', 'Flur'), ('Pausenhof', 'Pausenhof'), ('Schulweg', 'Schulweg'), ('Online', 'Online (WhatsApp, Instagram, Schul.Cloud...)'), ('Woanders', 'Woanders')], max_length=20, verbose_name='Ort')),
                ('konfliktpartei', models.CharField(choices=[('Schüler', 'Schüler (eine Person, Männlich)'), ('Schülerin', 'Schülerin (eine Person, Weiblich)'), ('Schüler*innen', 'Schüler*innen (Mehrzahl)'), ('Lehrer', 'ein Lehrer (Männlich)'), ('Lehrerin', 'eine Lehrerin (weiblich)'), ('Lehrer*innen', 'Lehrer*innen (Mehrzahl)'), ('Eltern', 'Eltern'), ('Schulpersonal', 'Schulpersonal'), ('Andere', 'Andere')], max_length=20, verbose_name='Konfliktpartei')),
                ('status', models.CharField(choices=[('positiv_geschlossen', 'Positiv geschlossen'), ('negativ_geschlossen', 'Negativ geschlossen'), ('offen', 'Offen'), ('abgelehnt', 'Abgelehnt')], default='offen', max_length=20, verbose_name='Status')),
                ('beschreibung', models.TextField(validators=[meldung.models.validate_char_count], verbose_name='Beschreibung')),
            ],
        ),
    ]
