# Generated by Django 4.2.16 on 2024-10-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meldung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fall',
            name='status',
            field=models.CharField(choices=[('positiv_geschlossen', 'Positiv geschlossen'), ('negativ_geschlossen', 'Negativ geschlossen'), ('offen', 'Offen'), ('abgelehnt', 'Abgelehnt')], default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
